### ISSUE TITLE
Migrate process features to v2

### ISSUE THREAD

**Issue by nh758** [digi-serve/ab_service_process_manager#6]
- [x] digi-serve/planning#476
- [x] digi-serve/planning#73
- [x] digi-serve/planning#473
